DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id VARCHAR(32) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	document VARCHAR(255) NOT NULL,
	document_type VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
